"""Prepare a fixed-panel, future-date protocol; never consume future returns."""
from pathlib import Path
from datetime import datetime,timezone
from zoneinfo import ZoneInfo
import json,hashlib
ROOT=Path(__file__).parent;ET=ZoneInfo('America/New_York')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,o):(ROOT/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
def main():
    assert not (ROOT/'protocol.json').exists()
    broad=ROOT.parent/'s500-broad-20261006';old=ROOT.parent/'s500-flush-rebound-20261007'
    original=json.loads((broad/'universe.json').read_text());classes=json.loads((old/'universe-classification.json').read_text())['population']
    lookup={x['symbol']:x['current_etf_classification'] for x in classes}
    assert len(original)==len(lookup)==6633 and len({x['symbol'] for x in original})==6633
    flags={'explicit_current_ETF_Y':'Y','explicit_current_ETF_N':'N','current_ETF_classification_unknown':'unknown'}
    panel=sorted([{'symbol':x['symbol'],'etf_classification':flags[lookup[x['symbol']]]} for x in original],key=lambda x:x['symbol'])
    save('fixed-panel.json',panel)
    source=[{'ancestor':'broad_20261006','name':'universe.json','sha256':sha(broad/'universe.json')},{'ancestor':'flush_rebound_20261007','name':'universe-classification.json','sha256':sha(old/'universe-classification.json')}]
    save('fixed-panel-source.json',{'symbols':6633,'source_directory_asof':'2026-10-06','frozen_panel_for_future_dates':True,'daily_refreshed_directory':False,'sources':source,'panel_sha256':sha(ROOT/'fixed-panel.json'),'limits':['New listings excluded throughout this version.','Known historical survivorship and symbol-reuse limitations persist.','ETF labels are frozen historical directory labels, not daily updated instrument guarantees.','No has_options or tradable flag is used as an additional outcome filter.']})
    cal=json.loads((ROOT/'calendar-sessions.json').read_text());sessions=[];days=[r['date'] for r in cal]
    now=datetime.now(timezone.utc);assert now.astimezone(ET).date().isoformat()<'2026-10-08'
    for i,r in enumerate(cal):
        if r['date']<'2026-10-08':continue
        assert i>=20
        def stamp(t):return datetime.fromisoformat(r['date']+'T'+t).replace(tzinfo=ET).astimezone(timezone.utc).isoformat()
        sessions.append({'ordinal':len(sessions)+1,'date':r['date'],'open_et':r['open'],'close_et':r['close'],'open_utc':stamp(r['open']),'close_utc':stamp(r['close']),'preopen_cutoff_utc':stamp('09:20'),'receipt_deadline_utc':stamp('17:15'),'review_at_utc':stamp('17:30'),'prior20_dates':days[i-20:i]})
    assert len(sessions)==59 and sessions[-1]['date']=='2026-12-31'
    protocol={'id':'s500_prospective_flush_fixed_panel_v1','status':'draft_before_validation_and_registration','prepared_at':now.isoformat(),'parent_commit':'f3274a94e16c00beae81094d3ec0410c826b6583','price_history_already_seen_through':'2026-10-06','registration_day_excluded':'2026-10-07','timezone':'America/New_York','window':['2026-10-08','2026-12-31'],'calendar_source_sha256':sha(ROOT/'calendar-source.json'),'calendar_sha256':sha(ROOT/'calendar-sessions.json'),'fixed_panel_sha256':sha(ROOT/'fixed-panel.json'),'fixed_panel_symbols':6633,'sessions':sessions,'review_ordinals':[20,40,59],'reviews':[{'ordinal':i,'date':sessions[i-1]['date'],'at_et':'17:30','purpose':'final_primary_endpoint' if i==59 else 'descriptive_progress_no_retuning'} for i in [20,40,59]],
      'observation_type':'Future unseen dates with preopen fixed-panel eligibility seals and post-close retrospective SIP bars; not real-time as-received or fill validation.',
      'selection':{'panel':'fixed6633plusforcedSPYQQQ, no new symbols promoted during version','prior_history':'exactly20 immediately preceding registered calendar sessions','prior_close_minimum':'5','median_close_times_volume_minimum':'20000000','top_liquidity':64,'remaining_hash_sample':32,'hash_namespace':'s500_flush_v1','storage':['MU','STX','WDC','SNDK','NTAP','RMBS','SIMO','P'],'controls':['SPY','QQQ'],'etf_unknown':'retain tagged unknown; explicit Y excluded from stocks; controls never stock','source_completeness':'All fixed-panel symbol requests and every pagination chain must finish before selection; omitted price history is a stock-level reason only if the request itself completed. No partial-pool ranking.'},
      'timing':{'preopen_window_et':['00:00','09:20'],'preopen_seal_deadline_et':'09:20','daily_input':'Same-session capture of prior sessions only, SIP/raw/1Day; last input date strictly before target date. Source requested_at and received_at both recorded.','postclose_window':'session_close_plus_15minutes through17:15ET on same date','primary_source_version':'first complete source bundle within window; append later versions as amendments, never silently replace primary','receipt_deadline_et':'17:15','review_time_et':'17:30','timestamps':'Executor receipt logs, not cryptographically authenticated historical delivery proofs; bar event_time alone cannot establish live availability.'},
      'inherited_variants':[[d,f,h,c] for d in ['0.02','0.03'] for f in ['FIXED','REBOUND'] for h in ['30m','60m','close_minus_10m'] for c in [5,10,25]],'primary_variant':['0.02','REBOUND','60m',10],
      'market_classification':{'primary':'SPY','sensitivity':'QQQ','definition':'Complete0..29 stock prefix earliest min-close t_min; benchmark close at same t_min/open0-1 <= -0.005 inclusive => market_down, otherwise market_not_down; any invalid/incomplete prefix unknown.','groups':['market_down','market_not_down','unknown'],'benchmark_targets_excluded_from_stock_statistics':True},
      'feature_bins':{'gap':['le_minus_2pct','minus_2pct_to_below_zero','zero_or_positive','unknown'],'close29':['le_minus_2pct','minus_2pct_to_below_zero','zero_or_positive','unknown'],'trough':['minute0_9','minute10_19','minute20_29','unknown'],'information_time':'All first30 bars end10:00ET; with postclose sources this is an event-time descriptor, not proof of live receipt.','all_bins_reported':True,'no_winning_bin_promotion':True},
      'outcomes':{'primary_endpoint':'At final calendar endpoint: arithmetic mean of per-date complete SPYdown primary target net stock-proxy returns; nonempty dates equally weighted. Empty dates not zeros.','no_automatic_pass_fail_or_trading_activation':True,'evidence_label_minimum_distinct_complete_outcome_dates':20,'evidence_label_scope':'Operational sample-size label only, not independent-date proof, power calculation or significance threshold. Fewer dates = insufficient sample, never replace the fixed end date.','interval':'Final-only descriptive95% percentile bootstrap of complete date means,2000 whole-date draws, deterministic SHA256 first16hex seed s500_prospective_flush_fixed_panel_v1|primary_final, linear interpolation. n<2 no interval. Serial dependence and finite-date coverage remain; interval alone does not validate options or strategy.','checkpoints':'20/40 report counts/missingness/all fixed-bin point estimates without new intervals or tuning. Calendar reviews do not wait for profitable signals.','secondary':['event_equal_net','all36variants','QQQ','same_timeSPYQQQreturns','original_three_peer_matched_excess','all_fixed_bins','positive_and_negative_tails'],'peers':'Original first30 nonflush eligible peers by absolute log prior liquidity distance, symbol ties, choose3 before checking future returns, never replace missing peers.','multiplicity':'One declared final primary endpoint; all other slices descriptive and cannot be selected as a validation winner.','costs':'Preserve5/10/25bp per side; already net returns are not charged twice; no option cost substitution.'},
      'missing_and_revisions':{'calendar':'Every planned date stays in ledger, even no run/no signal/unknown. Calendar changed/closure recorded as append-only operational deviation; no substitute dates.','preopen_missed':'No primary eligible selection for this date; do not reconstruct preopen seals after observing returns.','postclose_missed_or_failed':'Preserve sealed cases with unknown outcomes and source failure reason. Do not fill zero, rerank or replace.','no_signal':'Distinct from missing observations; an observed no-flush or no-rebound is not a zero-return trade.','late_data':'Record first-seen time and supersedes links in separate amended ledger; no retrospective promotion to primary.','early_stop':'No performance-based shortening/extension. Technical outages may pause acquisition, not erase failed dates.'},
      'operational_status':{'registration_is_not_scheduler':True,'new_scheduler':False,'future_capture_automatically_connected':False,'existing_observer_not_ai_research':True},'user_constraints':{'paper_initial_per_round':500,'paper_target':10000,'no_minimum_40_percent_winrate':True,'preserve_all_tail_winners_and_losses':True,'count_all_failures_residuals_and_reinjections_in_future_wealth_models':True,'funded_portfolio_or_option_profit_claim':False,'orders_sent':0,'account_reads':0,'vendor_purchase':False},'limitations':['Frozen directory cohort excludes future listings and retains known historical survivorship and symbol-identity problems.','Retrospective postclose SIP values may be revised and do not reconstruct what an intraday agent received.','Future primary outcome dates can be scarce or correlated.','Source outages and complete-window conditioning remain selection limitations.','Actual option contracts, bidask, whole-contract affordability and execution are unverified.']}
    protocol['fixed_panel_content_digest']=hashlib.sha256(json.dumps(panel,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()
    protocol['outcomes']['peers']='Only among same-date sealed selected stock_eligible cases, excluding target and SPY/QQQ: complete valid first30 prefix not reaching the SAME 2% or3% threshold; rank absolute log prior liquidity distance then symbol, choose3 before checking future returns, never replace missing peers.'
    protocol['timing']['primary_source_version']='First bundle in window with all required requests/pages completed, irrespective of individual missing/invalid bars or holding-window availability. Freeze that version even with unknown outcomes; later revisions separate, never wait for a more profitable or gap-free version.'
    protocol['feature_bins']['definitions']='gap=open0/sealed_prior_close-1; close29=close[29]/open0-1; trough=earliest integer0..29 attaining minimum first30 close. Complete unique valid first30 required; absent prior_close makes only gap unknown. Use exact raw-price cross-products for <=-0.02,(-0.02,0),>=0, and integer trough0..9/10..19/20..29. No display-rounded boundaries.'
    protocol['timing']['offline_review']='Verification/analysis/review may happen after receipt_deadline provided original preopen seal and source requested_at/received_at met their windows. Running late cannot fabricate an earlier seal/receipt.'
    protocol['selection']['numeric_safety']='Decimal encoding coefficient at most80digits and absolute exponent at most100; values outside these parser-safety limits are invalid prior20 inputs, not additional financial price thresholds.'
    save('protocol.json',protocol)
    print(json.dumps({'prepared_sessions':len(sessions),'reviews':protocol['reviews'],'fixed_panel':len(panel),'status':protocol['status']}))
if __name__=='__main__':main()
