import datetime, hashlib, json, pathlib, re, os

BASE = pathlib.Path(__file__).resolve().parent
manifest=json.loads((BASE/'manifest.json').read_text())
shell_ids={'opra','pricing','mbp1','terms','llms','docs-llms'}
for doc in manifest:
    doc['content_classification']='javascript_shell_content_unknown' if doc['id'] in shell_ids else 'official_public_sdk_source_documentation'
    doc['interpretation']='HTTP 200 does not establish requested page exists or its contents; no JavaScript execution or access-control bypass attempted.' if doc['id'] in shell_ids else 'Official vendor-maintained source code and docstrings; generic format/API evidence, not account entitlement or market-data coverage proof.'
(BASE/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
docs={x['id']:x for x in manifest}
def evidence(doc_id, quote):
    source=(BASE/'private'/'raw'/(doc_id+'.body')).read_text()
    if quote not in source: raise ValueError((doc_id,quote))
    d=docs[doc_id]
    return {'document_id':doc_id,'url':d['final_url'],'retrieved_at_utc':d['retrieved_at_utc'],'body_sha256':d['body_sha256'],'quote':quote,'source_line':source[:source.index(quote)].count('\n')+1}
e=[]
def claim(cid,status,finding,ev,limits=None):
    e.append({'id':cid,'status':status,'finding':finding,'evidence':[evidence(*q) for q in ev],'limitations':limits or []})
claim('opra_dataset_identity','partially_verified','The official SDK names the dataset OPRA.PILLAR. This confirms an identifier, not the historical start, end, availability or scope of U.S. options contracts.', [('publishers-sdk','OPRA_PILLAR = "OPRA.PILLAR"'),('metadata-sdk',"Request the available range for the dataset given the user's")], ['No authenticated metadata.get_dataset_range call was made.','2026-01-02 through 2026-10-05 coverage and completeness remain unverified.'])
claim('documentation_failure','verified_observation','OPRA dataset, MBP-1, pricing, terms, and two text-documentation discovery URLs returned HTTP 200 JavaScript shells; their requested content is unknown.', [('opra','You need to enable JavaScript to run this app')], ['Repeated shell hashes are preserved in manifest.json; HTTP 200 is not evidence of product coverage or legal terms.','No browser execution, hidden API reconstruction, login, or bypass was attempted.'])
claim('quote_trade_sampling_distinction','verified_generic_format','Generic DBN schemas distinguish cmbp-1 consolidated BBO, interval-sampled cbbo-1s/cbbo-1m, and tbbo/tcbbo observations at trade events. trades and OHLCV are trade-price products. The public source does not establish which schemas are available for OPRA.PILLAR or their date ranges.', [('enums-dbn','/// Consolidated best bid and offer.'),('enums-dbn','/// Consolidated best bid and offer subsampled at one-second intervals, in addition to'),('enums-dbn','/// Consolidated best bid and offer subsampled at one-minute intervals, in addition to'),('enums-dbn','/// All trade events with the consolidated best bid and offer (CBBO) immediately **before**'),('enums-dbn','/// All trade events with the best bid and offer (BBO) immediately **before**')], ['Use metadata.list_schemas for OPRA.PILLAR after account authorization, then validate whether quote-event completeness and venue scope meet S500 needs.','Sampled BBO or trade-event BBO cannot be assumed to preserve every intraday quote update.'])
claim('fields_timestamps_sizes','verified_generic_format','Generic consolidated BBO records include bid/ask price, bid/ask size and best-bid/ask publisher IDs. RecordHeader has ts_event in nanoseconds, Cmbp1Msg has ts_recv in nanoseconds, and flags describe message characteristics and data quality. In CbboMsg, price/size are last-trade fields; quotes live in levels. This is format-level evidence only.', [('records-dbn','pub bid_px: i64,'),('records-dbn','pub ask_px: i64,'),('records-dbn','pub bid_sz: u32,'),('records-dbn','pub ask_sz: u32,'),('records-dbn','/// The publisher ID indicating the venue containing the best bid.'),('records-dbn','/// The matching-engine-received timestamp expressed as the number of nanoseconds'),('records-dbn','/// The capture-server-received timestamp expressed as the number of nanoseconds'),('records-dbn','/// A bit field indicating event end, message characteristics, and data quality.'),('records-dbn','/// The last trade price price where every 1 unit corresponds to 1e-9, i.e. 1/1,000,000,000')], ['Venue-specific OPRA timestamp semantics, quote-condition mappings, sequence guarantees and underlying feed normalization remain unverified.','Normalized flags are not proof that all raw OPRA quote-condition codes survive.','No sample quote records were downloaded or inspected.'])
claim('point_in_time_contracts','partially_verified','The official client README advertises point-in-time instrument definitions without retroactive adjustment. The generic definition record includes activation, expiration, raw_symbol, underlying and strike fields. Symbology resolution accepts inclusive start_date and exclusive end_date.', [('python-readme','[Point-in-time]() instrument definitions, free of look-ahead bias and retroactive adjustments.'),('records-dbn','pub expiration: u64,'),('records-dbn','pub activation: u64,'),('records-dbn','pub raw_symbol: [c_char; SYMBOL_CSTR_LEN],'),('symbology-sdk','The inclusive UTC start date of the request range.'),('symbology-sdk','The exclusive UTC end date of the request range.')], ['The generic fields do not confirm they are populated for OPRA.PILLAR.','Corporate-action/split deliverables, adjusted-option identifiers, nonstandard multipliers and expired-contract completeness for the S500 universe remain unverified.','Do not infer shares deliverable from a generic contract_multiplier field: its source comment refers to deliverable peak days and units hours/days.','No current-contract list should be substituted for a historical contract universe.'])
claim('cost_and_entitlement','unknown_amount','No current dollar price, required subscription tier or complete task cost was confirmed. The official SDK exposes unit-price, available-range and cost metadata methods. get_cost is request-specific and respects discounts from flat-rate plans.', [('metadata-sdk','List unit prices for each feed mode and data schema in US dollars per'),('metadata-sdk','Request the cost in US dollars for historical streaming or batched'),('metadata-sdk','rate plans.')], ['Public pricing returned a JavaScript shell.','No account, API key, authorized quote request or data purchase exists for this research.','The SDK get_cost docstring says GET but implementation uses _post; use the supported SDK method rather than inferring an HTTP verb from the docstring.','A cost result requires the exact symbol universe, schema, start/end, entitlement and request limit; no numeric estimate was invented.'])
claim('licensing_rights','unknown','Market-data rights for individual/nonprofessional status, historical storage, cloud research, derived outputs and redistribution were not established. The README Apache 2.0 statement concerns the client software and is not a market-data license.', [('python-readme','Distributed under the [Apache 2.0 License]'),('terms','You need to enable JavaScript to run this app')], ['Obtain applicable Databento and OPRA historical-use terms before any acquisition.','Do not infer redistribution, public artifact inclusion, team sharing or indefinite storage rights.'])
claim('cloud_and_auth','partially_verified','Databento supports a Python historical HTTP client and API-key authentication through DATABENTO_API_KEY. Its synchronous HTTP source uses requests with HTTP Basic auth, placing the key as username and an empty password. This suggests a normal HTTPS cloud workflow without a desktop terminal, but authenticated compatibility has not been tested.', [('python-readme','The official Python client library for [Databento]'),('python-readme','- python = "^3.10"'),('historical-client-sdk','If `None` then the `DATABENTO_API_KEY` environment variable is used.'),('http-sdk','auth=HTTPBasicAuth(username=self._key, password="") if basic_auth else None,')], ['Only public documentation HTTPS through the inherited proxy was verified; no Databento API endpoint or authenticated call was tested.','Environment metadata contains no Databento credential binding. Existing Alpaca secrets were not read or reused.','Verify the selected gateway hostname and proxy credential-injection compatibility with encoded Basic auth before adding a destination-scoped secret.','Prefer the supported synchronous historical path when preserving inherited proxy behavior; asynchronous client code does not visibly set aiohttp trust_env in inspected source.','No SDK or terminal was installed and no environment configuration changed.'])
claim('time_range_filter','verified_generic_api','timeseries.get_range start is inclusive and end exclusive, filtering ts_recv where present and otherwise ts_event; naive times are assumed UTC.', [('timeseries-sdk','The inclusive start of the request range.'),('timeseries-sdk','The exclusive end of the request range.'),('timeseries-sdk','Filters on `ts_recv` if it exists in the schema, otherwise `ts_event`.'),('timeseries-sdk','Assumes UTC as timezone unless passed a tz-aware object.')], ['Use explicit UTC instants converted from the intended exchange-local sessions; a UTC date interval is not itself proof of a complete U.S. trading session.','A whole-date target through 2026-10-05 nominally has exclusive end 2026-10-06, subject to verified session boundaries.'])
result={'vendor':'Databento','research_scope':'Read-only official public documentation for historical US options bid/ask, S500, 2026-01-02 through 2026-10-05 inclusive','generated_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z'),'retrieval_count':len(manifest),'source_classes':{'javascript_shells':6,'official_sdk_source_documents':9},'claims':e,'recommendation':{'decision':'Retain as a technically plausible conditional candidate; not procurement-ready from this evidence.','path':['After vendor selection, obtain readable applicable OPRA/Databento historical license, plan and current price terms.','Confirm OPRA.PILLAR availability, schema-specific date range and contract-definition population for 2026-01-02 through 2026-10-05.','Create a destination-scoped Databento credential binding only with user authorization; verify Basic-auth compatibility with the environment proxy.','Use metadata.list_schemas and metadata.get_dataset_range, then metadata.get_cost for an explicit historical contract universe and dates; do not request all symbols or download broad data merely to price it.','If coverage, rights and cost are accepted, validate one already-authorized narrowly scoped historical quote slice and accompanying point-in-time definition, then assess gaps, timestamps, condition treatment and split deliverables.'],'selection_caveat':'A competitor with readable 2026 coverage, quote-plan entitlement and historical license evidence can be advanced first; compare acquired sample quality only after authorization.'},'actions_performed':{'public_document_requests':15,'authenticated_vendor_requests':0,'market_data_downloads':0,'subscriptions_or_purchases':0,'account_signups_or_logins':0,'sdk_or_terminal_installations':0,'environment_config_mutations':0},'manifest':'manifest.json','raw_response_policy':'Raw bodies and derived full text retained in private/ only; publish findings and manifest, not raw responses.','limitations':['No proof of source coverage completeness or specific S500 options availability.','No numeric dataset cost or market-data redistribution/storage grant confirmed.','Official main-branch source is mutable; body SHA-256 and UTC retrieval time pin the observed evidence.']}
(BASE/'findings.json').write_text(json.dumps(result,indent=2)+'\n')
md=['# Databento — historical US options quote-source review','', 'Target: 2026-01-02 through 2026-10-05. Read-only public documentation research; no account, API call, market-data download, install or purchase.','', '**Decision:** retain as a conditional technical candidate. Coverage dates, dataset-specific schemas, current price and licensed use remain unverified.','', 'The official OPRA, MBP-1, pricing and terms pages returned HTTP 200 JavaScript shells. Two text-documentation discovery URLs returned the same shell. Those are preserved as content unknown. Official vendor-maintained GitHub source and docstrings supplied the generic format/API evidence below.','']
for c in e:
    md += [f"## {c['id'].replace('_',' ').capitalize()}",'',f"Status: {c['status']}.",'',c['finding'],'']
    for q in c['evidence'][:3]:
        md += [f"- [{q['document_id']}]({q['url']}), retrieved {q['retrieved_at_utc']}, source line {q['source_line']}: “{q['quote']}”",f"  Body SHA-256: `{q['body_sha256']}`"]
    md+=['']
    for l in c['limitations']: md += [f'- {l}']
    md+=['']
md += ['## Proposed next step','']+[f'{i+1}. {s}' for i,s in enumerate(result['recommendation']['path'])]+['','Evidence: `manifest.json` records all 15 public URLs, exact retrieval times, HTTP outcomes and body SHA-256 values. `findings.json` contains all claim quotations. Raw material remains private.','']
(BASE/'findings.md').write_text('\n'.join(md))
for path in (BASE/'private').rglob('*'):
    os.chmod(path,0o700 if path.is_dir() else 0o600)
os.chmod(BASE/'private',0o700)
for d in manifest:
    actual=hashlib.sha256((BASE/d['private_raw_relative_path']).read_bytes()).hexdigest()
    if actual!=d['body_sha256']: raise ValueError(d['id'])
assert len(manifest)==15
print(json.dumps({'documents':len(manifest),'claims':len(e),'hashes_verified':True,'output_files':['manifest.json','findings.json','findings.md']}))
